// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.21.9
// source: pics_struct.proto

package stub

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetPicCategoryReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId int32  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Openid string `protobuf:"bytes,2,opt,name=openid,proto3" json:"openid,omitempty"`
}

func (x *GetPicCategoryReq) Reset() {
	*x = GetPicCategoryReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pics_struct_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPicCategoryReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPicCategoryReq) ProtoMessage() {}

func (x *GetPicCategoryReq) ProtoReflect() protoreflect.Message {
	mi := &file_pics_struct_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPicCategoryReq.ProtoReflect.Descriptor instead.
func (*GetPicCategoryReq) Descriptor() ([]byte, []int) {
	return file_pics_struct_proto_rawDescGZIP(), []int{0}
}

func (x *GetPicCategoryReq) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetPicCategoryReq) GetOpenid() string {
	if x != nil {
		return x.Openid
	}
	return ""
}

type GetPicCategoryRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	List []*Photo `protobuf:"bytes,3,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *GetPicCategoryRsp) Reset() {
	*x = GetPicCategoryRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pics_struct_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPicCategoryRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPicCategoryRsp) ProtoMessage() {}

func (x *GetPicCategoryRsp) ProtoReflect() protoreflect.Message {
	mi := &file_pics_struct_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPicCategoryRsp.ProtoReflect.Descriptor instead.
func (*GetPicCategoryRsp) Descriptor() ([]byte, []int) {
	return file_pics_struct_proto_rawDescGZIP(), []int{1}
}

func (x *GetPicCategoryRsp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetPicCategoryRsp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *GetPicCategoryRsp) GetList() []*Photo {
	if x != nil {
		return x.List
	}
	return nil
}

type Photo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Pid     string `protobuf:"bytes,2,opt,name=pid,proto3" json:"pid,omitempty"`
	Ename   string `protobuf:"bytes,3,opt,name=ename,proto3" json:"ename,omitempty"`
	Zname   string `protobuf:"bytes,4,opt,name=zname,proto3" json:"zname,omitempty"`
	Address string `protobuf:"bytes,5,opt,name=address,proto3" json:"address,omitempty"`
}

func (x *Photo) Reset() {
	*x = Photo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pics_struct_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Photo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Photo) ProtoMessage() {}

func (x *Photo) ProtoReflect() protoreflect.Message {
	mi := &file_pics_struct_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Photo.ProtoReflect.Descriptor instead.
func (*Photo) Descriptor() ([]byte, []int) {
	return file_pics_struct_proto_rawDescGZIP(), []int{2}
}

func (x *Photo) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Photo) GetPid() string {
	if x != nil {
		return x.Pid
	}
	return ""
}

func (x *Photo) GetEname() string {
	if x != nil {
		return x.Ename
	}
	return ""
}

func (x *Photo) GetZname() string {
	if x != nil {
		return x.Zname
	}
	return ""
}

func (x *Photo) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

var File_pics_struct_proto protoreflect.FileDescriptor

var file_pics_struct_proto_rawDesc = []byte{
	0x0a, 0x11, 0x70, 0x69, 0x63, 0x73, 0x5f, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x04, 0x73, 0x74, 0x75, 0x62, 0x22, 0x44, 0x0a, 0x11, 0x47, 0x65, 0x74,
	0x50, 0x69, 0x63, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x71, 0x12, 0x17,
	0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x70, 0x65, 0x6e, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6f, 0x70, 0x65, 0x6e, 0x69, 0x64, 0x22,
	0x5a, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x50, 0x69, 0x63, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72,
	0x79, 0x52, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x1f, 0x0a, 0x04, 0x6c, 0x69,
	0x73, 0x74, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x73, 0x74, 0x75, 0x62, 0x2e,
	0x50, 0x68, 0x6f, 0x74, 0x6f, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x22, 0x6f, 0x0a, 0x05, 0x50,
	0x68, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x70, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x70, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x7a, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x7a, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x42, 0x08, 0x5a, 0x06,
	0x2e, 0x2f, 0x73, 0x74, 0x75, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pics_struct_proto_rawDescOnce sync.Once
	file_pics_struct_proto_rawDescData = file_pics_struct_proto_rawDesc
)

func file_pics_struct_proto_rawDescGZIP() []byte {
	file_pics_struct_proto_rawDescOnce.Do(func() {
		file_pics_struct_proto_rawDescData = protoimpl.X.CompressGZIP(file_pics_struct_proto_rawDescData)
	})
	return file_pics_struct_proto_rawDescData
}

var file_pics_struct_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_pics_struct_proto_goTypes = []interface{}{
	(*GetPicCategoryReq)(nil), // 0: stub.GetPicCategoryReq
	(*GetPicCategoryRsp)(nil), // 1: stub.GetPicCategoryRsp
	(*Photo)(nil),             // 2: stub.Photo
}
var file_pics_struct_proto_depIdxs = []int32{
	2, // 0: stub.GetPicCategoryRsp.list:type_name -> stub.Photo
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pics_struct_proto_init() }
func file_pics_struct_proto_init() {
	if File_pics_struct_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pics_struct_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPicCategoryReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pics_struct_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPicCategoryRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pics_struct_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Photo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pics_struct_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pics_struct_proto_goTypes,
		DependencyIndexes: file_pics_struct_proto_depIdxs,
		MessageInfos:      file_pics_struct_proto_msgTypes,
	}.Build()
	File_pics_struct_proto = out.File
	file_pics_struct_proto_rawDesc = nil
	file_pics_struct_proto_goTypes = nil
	file_pics_struct_proto_depIdxs = nil
}
