// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.21.9
// source: pics_struct.proto

package stub

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetPicCategory1Req struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId int32  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Openid string `protobuf:"bytes,2,opt,name=openid,proto3" json:"openid,omitempty"`
}

func (x *GetPicCategory1Req) Reset() {
	*x = GetPicCategory1Req{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pics_struct_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPicCategory1Req) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPicCategory1Req) ProtoMessage() {}

func (x *GetPicCategory1Req) ProtoReflect() protoreflect.Message {
	mi := &file_pics_struct_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPicCategory1Req.ProtoReflect.Descriptor instead.
func (*GetPicCategory1Req) Descriptor() ([]byte, []int) {
	return file_pics_struct_proto_rawDescGZIP(), []int{0}
}

func (x *GetPicCategory1Req) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetPicCategory1Req) GetOpenid() string {
	if x != nil {
		return x.Openid
	}
	return ""
}

type GetPicCategory1Rsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	List []*Photo `protobuf:"bytes,3,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *GetPicCategory1Rsp) Reset() {
	*x = GetPicCategory1Rsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pics_struct_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPicCategory1Rsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPicCategory1Rsp) ProtoMessage() {}

func (x *GetPicCategory1Rsp) ProtoReflect() protoreflect.Message {
	mi := &file_pics_struct_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPicCategory1Rsp.ProtoReflect.Descriptor instead.
func (*GetPicCategory1Rsp) Descriptor() ([]byte, []int) {
	return file_pics_struct_proto_rawDescGZIP(), []int{1}
}

func (x *GetPicCategory1Rsp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetPicCategory1Rsp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *GetPicCategory1Rsp) GetList() []*Photo {
	if x != nil {
		return x.List
	}
	return nil
}

type Photo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Pid     string `protobuf:"bytes,2,opt,name=pid,proto3" json:"pid,omitempty"`
	Ename   string `protobuf:"bytes,3,opt,name=ename,proto3" json:"ename,omitempty"`
	Zname   string `protobuf:"bytes,4,opt,name=zname,proto3" json:"zname,omitempty"`
	Address string `protobuf:"bytes,5,opt,name=address,proto3" json:"address,omitempty"`
}

func (x *Photo) Reset() {
	*x = Photo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pics_struct_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Photo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Photo) ProtoMessage() {}

func (x *Photo) ProtoReflect() protoreflect.Message {
	mi := &file_pics_struct_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Photo.ProtoReflect.Descriptor instead.
func (*Photo) Descriptor() ([]byte, []int) {
	return file_pics_struct_proto_rawDescGZIP(), []int{2}
}

func (x *Photo) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Photo) GetPid() string {
	if x != nil {
		return x.Pid
	}
	return ""
}

func (x *Photo) GetEname() string {
	if x != nil {
		return x.Ename
	}
	return ""
}

func (x *Photo) GetZname() string {
	if x != nil {
		return x.Zname
	}
	return ""
}

func (x *Photo) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type GetPicList1Req struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Typeid string `protobuf:"bytes,1,opt,name=typeid,proto3" json:"typeid,omitempty"`
	Limit  int32  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Skip   int32  `protobuf:"varint,3,opt,name=skip,proto3" json:"skip,omitempty"` //类型
}

func (x *GetPicList1Req) Reset() {
	*x = GetPicList1Req{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pics_struct_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPicList1Req) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPicList1Req) ProtoMessage() {}

func (x *GetPicList1Req) ProtoReflect() protoreflect.Message {
	mi := &file_pics_struct_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPicList1Req.ProtoReflect.Descriptor instead.
func (*GetPicList1Req) Descriptor() ([]byte, []int) {
	return file_pics_struct_proto_rawDescGZIP(), []int{3}
}

func (x *GetPicList1Req) GetTypeid() string {
	if x != nil {
		return x.Typeid
	}
	return ""
}

func (x *GetPicList1Req) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetPicList1Req) GetSkip() int32 {
	if x != nil {
		return x.Skip
	}
	return 0
}

type GetHotPicList1Req struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Limit int32 `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Skip  int32 `protobuf:"varint,2,opt,name=skip,proto3" json:"skip,omitempty"` //类型
}

func (x *GetHotPicList1Req) Reset() {
	*x = GetHotPicList1Req{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pics_struct_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetHotPicList1Req) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHotPicList1Req) ProtoMessage() {}

func (x *GetHotPicList1Req) ProtoReflect() protoreflect.Message {
	mi := &file_pics_struct_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHotPicList1Req.ProtoReflect.Descriptor instead.
func (*GetHotPicList1Req) Descriptor() ([]byte, []int) {
	return file_pics_struct_proto_rawDescGZIP(), []int{4}
}

func (x *GetHotPicList1Req) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetHotPicList1Req) GetSkip() int32 {
	if x != nil {
		return x.Skip
	}
	return 0
}

type GetPicList1Rsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int32       `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg  string      `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	List []*PicList1 `protobuf:"bytes,3,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *GetPicList1Rsp) Reset() {
	*x = GetPicList1Rsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pics_struct_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPicList1Rsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPicList1Rsp) ProtoMessage() {}

func (x *GetPicList1Rsp) ProtoReflect() protoreflect.Message {
	mi := &file_pics_struct_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPicList1Rsp.ProtoReflect.Descriptor instead.
func (*GetPicList1Rsp) Descriptor() ([]byte, []int) {
	return file_pics_struct_proto_rawDescGZIP(), []int{5}
}

func (x *GetPicList1Rsp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetPicList1Rsp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *GetPicList1Rsp) GetList() []*PicList1 {
	if x != nil {
		return x.List
	}
	return nil
}

type PicList1 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pid         int32   `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	Imageid     string  `protobuf:"bytes,2,opt,name=imageid,proto3" json:"imageid,omitempty"`
	ImageSmall  string  `protobuf:"bytes,3,opt,name=image_small,json=imageSmall,proto3" json:"image_small,omitempty"`
	ImageMiddle string  `protobuf:"bytes,4,opt,name=image_middle,json=imageMiddle,proto3" json:"image_middle,omitempty"`
	ImageBig    string  `protobuf:"bytes,5,opt,name=image_big,json=imageBig,proto3" json:"image_big,omitempty"`
	Tags        []*Tags `protobuf:"bytes,6,rep,name=tags,proto3" json:"tags,omitempty"`
	Desc        string  `protobuf:"bytes,7,opt,name=desc,proto3" json:"desc,omitempty"`
}

func (x *PicList1) Reset() {
	*x = PicList1{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pics_struct_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PicList1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PicList1) ProtoMessage() {}

func (x *PicList1) ProtoReflect() protoreflect.Message {
	mi := &file_pics_struct_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PicList1.ProtoReflect.Descriptor instead.
func (*PicList1) Descriptor() ([]byte, []int) {
	return file_pics_struct_proto_rawDescGZIP(), []int{6}
}

func (x *PicList1) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *PicList1) GetImageid() string {
	if x != nil {
		return x.Imageid
	}
	return ""
}

func (x *PicList1) GetImageSmall() string {
	if x != nil {
		return x.ImageSmall
	}
	return ""
}

func (x *PicList1) GetImageMiddle() string {
	if x != nil {
		return x.ImageMiddle
	}
	return ""
}

func (x *PicList1) GetImageBig() string {
	if x != nil {
		return x.ImageBig
	}
	return ""
}

func (x *PicList1) GetTags() []*Tags {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *PicList1) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

type Tags struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id  int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Tag string `protobuf:"bytes,2,opt,name=tag,proto3" json:"tag,omitempty"`
}

func (x *Tags) Reset() {
	*x = Tags{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pics_struct_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Tags) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tags) ProtoMessage() {}

func (x *Tags) ProtoReflect() protoreflect.Message {
	mi := &file_pics_struct_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tags.ProtoReflect.Descriptor instead.
func (*Tags) Descriptor() ([]byte, []int) {
	return file_pics_struct_proto_rawDescGZIP(), []int{7}
}

func (x *Tags) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Tags) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

var File_pics_struct_proto protoreflect.FileDescriptor

var file_pics_struct_proto_rawDesc = []byte{
	0x0a, 0x11, 0x70, 0x69, 0x63, 0x73, 0x5f, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x04, 0x73, 0x74, 0x75, 0x62, 0x22, 0x45, 0x0a, 0x12, 0x47, 0x65, 0x74,
	0x50, 0x69, 0x63, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x31, 0x52, 0x65, 0x71, 0x12,
	0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x70, 0x65, 0x6e,
	0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6f, 0x70, 0x65, 0x6e, 0x69, 0x64,
	0x22, 0x5b, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x50, 0x69, 0x63, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f,
	0x72, 0x79, 0x31, 0x52, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73,
	0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x1f, 0x0a, 0x04,
	0x6c, 0x69, 0x73, 0x74, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x73, 0x74, 0x75,
	0x62, 0x2e, 0x50, 0x68, 0x6f, 0x74, 0x6f, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x22, 0x6f, 0x0a,
	0x05, 0x50, 0x68, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x70, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x70, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14,
	0x0a, 0x05, 0x7a, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x7a,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0x52,
	0x0a, 0x0e, 0x47, 0x65, 0x74, 0x50, 0x69, 0x63, 0x4c, 0x69, 0x73, 0x74, 0x31, 0x52, 0x65, 0x71,
	0x12, 0x16, 0x0a, 0x06, 0x74, 0x79, 0x70, 0x65, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x74, 0x79, 0x70, 0x65, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x12,
	0x0a, 0x04, 0x73, 0x6b, 0x69, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x73, 0x6b,
	0x69, 0x70, 0x22, 0x3d, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x48, 0x6f, 0x74, 0x50, 0x69, 0x63, 0x4c,
	0x69, 0x73, 0x74, 0x31, 0x52, 0x65, 0x71, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x12, 0x0a,
	0x04, 0x73, 0x6b, 0x69, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x73, 0x6b, 0x69,
	0x70, 0x22, 0x5a, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x50, 0x69, 0x63, 0x4c, 0x69, 0x73, 0x74, 0x31,
	0x52, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x22, 0x0a, 0x04, 0x6c, 0x69, 0x73,
	0x74, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x73, 0x74, 0x75, 0x62, 0x2e, 0x50,
	0x69, 0x63, 0x4c, 0x69, 0x73, 0x74, 0x31, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x22, 0xcb, 0x01,
	0x0a, 0x08, 0x50, 0x69, 0x63, 0x4c, 0x69, 0x73, 0x74, 0x31, 0x12, 0x10, 0x0a, 0x03, 0x70, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x70, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07,
	0x69, 0x6d, 0x61, 0x67, 0x65, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x69,
	0x6d, 0x61, 0x67, 0x65, 0x69, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x5f,
	0x73, 0x6d, 0x61, 0x6c, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x69, 0x6d, 0x61,
	0x67, 0x65, 0x53, 0x6d, 0x61, 0x6c, 0x6c, 0x12, 0x21, 0x0a, 0x0c, 0x69, 0x6d, 0x61, 0x67, 0x65,
	0x5f, 0x6d, 0x69, 0x64, 0x64, 0x6c, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x69,
	0x6d, 0x61, 0x67, 0x65, 0x4d, 0x69, 0x64, 0x64, 0x6c, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x6d,
	0x61, 0x67, 0x65, 0x5f, 0x62, 0x69, 0x67, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x69,
	0x6d, 0x61, 0x67, 0x65, 0x42, 0x69, 0x67, 0x12, 0x1e, 0x0a, 0x04, 0x74, 0x61, 0x67, 0x73, 0x18,
	0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x73, 0x74, 0x75, 0x62, 0x2e, 0x74, 0x61, 0x67,
	0x73, 0x52, 0x04, 0x74, 0x61, 0x67, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x65, 0x73, 0x63, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x65, 0x73, 0x63, 0x22, 0x28, 0x0a, 0x04, 0x74,
	0x61, 0x67, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x74, 0x61, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x74, 0x61, 0x67, 0x42, 0x08, 0x5a, 0x06, 0x2e, 0x2f, 0x73, 0x74, 0x75, 0x62, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pics_struct_proto_rawDescOnce sync.Once
	file_pics_struct_proto_rawDescData = file_pics_struct_proto_rawDesc
)

func file_pics_struct_proto_rawDescGZIP() []byte {
	file_pics_struct_proto_rawDescOnce.Do(func() {
		file_pics_struct_proto_rawDescData = protoimpl.X.CompressGZIP(file_pics_struct_proto_rawDescData)
	})
	return file_pics_struct_proto_rawDescData
}

var file_pics_struct_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_pics_struct_proto_goTypes = []interface{}{
	(*GetPicCategory1Req)(nil), // 0: stub.GetPicCategory1Req
	(*GetPicCategory1Rsp)(nil), // 1: stub.GetPicCategory1Rsp
	(*Photo)(nil),              // 2: stub.Photo
	(*GetPicList1Req)(nil),     // 3: stub.GetPicList1Req
	(*GetHotPicList1Req)(nil),  // 4: stub.GetHotPicList1Req
	(*GetPicList1Rsp)(nil),     // 5: stub.GetPicList1Rsp
	(*PicList1)(nil),           // 6: stub.PicList1
	(*Tags)(nil),               // 7: stub.tags
}
var file_pics_struct_proto_depIdxs = []int32{
	2, // 0: stub.GetPicCategory1Rsp.list:type_name -> stub.Photo
	6, // 1: stub.GetPicList1Rsp.list:type_name -> stub.PicList1
	7, // 2: stub.PicList1.tags:type_name -> stub.tags
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_pics_struct_proto_init() }
func file_pics_struct_proto_init() {
	if File_pics_struct_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pics_struct_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPicCategory1Req); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pics_struct_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPicCategory1Rsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pics_struct_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Photo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pics_struct_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPicList1Req); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pics_struct_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetHotPicList1Req); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pics_struct_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPicList1Rsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pics_struct_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PicList1); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pics_struct_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Tags); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pics_struct_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pics_struct_proto_goTypes,
		DependencyIndexes: file_pics_struct_proto_depIdxs,
		MessageInfos:      file_pics_struct_proto_msgTypes,
	}.Build()
	File_pics_struct_proto = out.File
	file_pics_struct_proto_rawDesc = nil
	file_pics_struct_proto_goTypes = nil
	file_pics_struct_proto_depIdxs = nil
}
