// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.21.9
// source: search_struct.proto

package stub

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetSearchReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Keyword string `protobuf:"bytes,1,opt,name=keyword,proto3" json:"keyword,omitempty"`
	Start   int32  `protobuf:"varint,2,opt,name=start,proto3" json:"start,omitempty"`
}

func (x *GetSearchReq) Reset() {
	*x = GetSearchReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_search_struct_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSearchReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSearchReq) ProtoMessage() {}

func (x *GetSearchReq) ProtoReflect() protoreflect.Message {
	mi := &file_search_struct_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSearchReq.ProtoReflect.Descriptor instead.
func (*GetSearchReq) Descriptor() ([]byte, []int) {
	return file_search_struct_proto_rawDescGZIP(), []int{0}
}

func (x *GetSearchReq) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *GetSearchReq) GetStart() int32 {
	if x != nil {
		return x.Start
	}
	return 0
}

type GetSearchRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int32         `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg  string        `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	List []*SearchList `protobuf:"bytes,3,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *GetSearchRsp) Reset() {
	*x = GetSearchRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_search_struct_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSearchRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSearchRsp) ProtoMessage() {}

func (x *GetSearchRsp) ProtoReflect() protoreflect.Message {
	mi := &file_search_struct_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSearchRsp.ProtoReflect.Descriptor instead.
func (*GetSearchRsp) Descriptor() ([]byte, []int) {
	return file_search_struct_proto_rawDescGZIP(), []int{1}
}

func (x *GetSearchRsp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetSearchRsp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *GetSearchRsp) GetList() []*SearchList {
	if x != nil {
		return x.List
	}
	return nil
}

type SearchList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sid    int32  `protobuf:"varint,1,opt,name=sid,proto3" json:"sid,omitempty"`
	Album  string `protobuf:"bytes,2,opt,name=album,proto3" json:"album,omitempty"`   //专辑
	Photo  string `protobuf:"bytes,3,opt,name=photo,proto3" json:"photo,omitempty"`   //壁纸
	Sender string `protobuf:"bytes,4,opt,name=sender,proto3" json:"sender,omitempty"` //头像
	Dates  string `protobuf:"bytes,5,opt,name=dates,proto3" json:"dates,omitempty"`   //时间
}

func (x *SearchList) Reset() {
	*x = SearchList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_search_struct_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchList) ProtoMessage() {}

func (x *SearchList) ProtoReflect() protoreflect.Message {
	mi := &file_search_struct_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchList.ProtoReflect.Descriptor instead.
func (*SearchList) Descriptor() ([]byte, []int) {
	return file_search_struct_proto_rawDescGZIP(), []int{2}
}

func (x *SearchList) GetSid() int32 {
	if x != nil {
		return x.Sid
	}
	return 0
}

func (x *SearchList) GetAlbum() string {
	if x != nil {
		return x.Album
	}
	return ""
}

func (x *SearchList) GetPhoto() string {
	if x != nil {
		return x.Photo
	}
	return ""
}

func (x *SearchList) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *SearchList) GetDates() string {
	if x != nil {
		return x.Dates
	}
	return ""
}

var File_search_struct_proto protoreflect.FileDescriptor

var file_search_struct_proto_rawDesc = []byte{
	0x0a, 0x13, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x5f, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x73, 0x74, 0x75, 0x62, 0x22, 0x3e, 0x0a, 0x0c, 0x47,
	0x65, 0x74, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x71, 0x12, 0x18, 0x0a, 0x07, 0x6b,
	0x65, 0x79, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6b, 0x65,
	0x79, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x22, 0x5a, 0x0a, 0x0c, 0x47,
	0x65, 0x74, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x63,
	0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12,
	0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73,
	0x67, 0x12, 0x24, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x10, 0x2e, 0x73, 0x74, 0x75, 0x62, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x4c, 0x69, 0x73,
	0x74, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x22, 0x78, 0x0a, 0x0a, 0x53, 0x65, 0x61, 0x72, 0x63,
	0x68, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x03, 0x73, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x6c, 0x62, 0x75, 0x6d,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x61, 0x6c, 0x62, 0x75, 0x6d, 0x12, 0x14, 0x0a,
	0x05, 0x70, 0x68, 0x6f, 0x74, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x68,
	0x6f, 0x74, 0x6f, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x64,
	0x61, 0x74, 0x65, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x64, 0x61, 0x74, 0x65,
	0x73, 0x42, 0x08, 0x5a, 0x06, 0x2e, 0x2f, 0x73, 0x74, 0x75, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_search_struct_proto_rawDescOnce sync.Once
	file_search_struct_proto_rawDescData = file_search_struct_proto_rawDesc
)

func file_search_struct_proto_rawDescGZIP() []byte {
	file_search_struct_proto_rawDescOnce.Do(func() {
		file_search_struct_proto_rawDescData = protoimpl.X.CompressGZIP(file_search_struct_proto_rawDescData)
	})
	return file_search_struct_proto_rawDescData
}

var file_search_struct_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_search_struct_proto_goTypes = []interface{}{
	(*GetSearchReq)(nil), // 0: stub.GetSearchReq
	(*GetSearchRsp)(nil), // 1: stub.GetSearchRsp
	(*SearchList)(nil),   // 2: stub.SearchList
}
var file_search_struct_proto_depIdxs = []int32{
	2, // 0: stub.GetSearchRsp.list:type_name -> stub.SearchList
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_search_struct_proto_init() }
func file_search_struct_proto_init() {
	if File_search_struct_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_search_struct_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSearchReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_search_struct_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSearchRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_search_struct_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_search_struct_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_search_struct_proto_goTypes,
		DependencyIndexes: file_search_struct_proto_depIdxs,
		MessageInfos:      file_search_struct_proto_msgTypes,
	}.Build()
	File_search_struct_proto = out.File
	file_search_struct_proto_rawDesc = nil
	file_search_struct_proto_goTypes = nil
	file_search_struct_proto_depIdxs = nil
}
