// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.5
// source: service.proto

package stub

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// FixServiceClient is the client API for FixService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FixServiceClient interface {
	//图片
	GetPicCategory(ctx context.Context, in *GetPicCategoryReq, opts ...grpc.CallOption) (*GetPicCategoryRsp, error)
}

type fixServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFixServiceClient(cc grpc.ClientConnInterface) FixServiceClient {
	return &fixServiceClient{cc}
}

func (c *fixServiceClient) GetPicCategory(ctx context.Context, in *GetPicCategoryReq, opts ...grpc.CallOption) (*GetPicCategoryRsp, error) {
	out := new(GetPicCategoryRsp)
	err := c.cc.Invoke(ctx, "/stub.FixService/GetPicCategory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FixServiceServer is the server API for FixService service.
// All implementations must embed UnimplementedFixServiceServer
// for forward compatibility
type FixServiceServer interface {
	//图片
	GetPicCategory(context.Context, *GetPicCategoryReq) (*GetPicCategoryRsp, error)
	mustEmbedUnimplementedFixServiceServer()
}

// UnimplementedFixServiceServer must be embedded to have forward compatible implementations.
type UnimplementedFixServiceServer struct {
}

func (UnimplementedFixServiceServer) GetPicCategory(context.Context, *GetPicCategoryReq) (*GetPicCategoryRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPicCategory not implemented")
}
func (UnimplementedFixServiceServer) mustEmbedUnimplementedFixServiceServer() {}

// UnsafeFixServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FixServiceServer will
// result in compilation errors.
type UnsafeFixServiceServer interface {
	mustEmbedUnimplementedFixServiceServer()
}

func RegisterFixServiceServer(s grpc.ServiceRegistrar, srv FixServiceServer) {
	s.RegisterService(&FixService_ServiceDesc, srv)
}

func _FixService_GetPicCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPicCategoryReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FixServiceServer).GetPicCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/stub.FixService/GetPicCategory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FixServiceServer).GetPicCategory(ctx, req.(*GetPicCategoryReq))
	}
	return interceptor(ctx, in, info, handler)
}

// FixService_ServiceDesc is the grpc.ServiceDesc for FixService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FixService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "stub.FixService",
	HandlerType: (*FixServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPicCategory",
			Handler:    _FixService_GetPicCategory_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}
